### PR TITLE
aws-sdk-go version bump, 1.37.10 -> 1.42.0

### PR DESCRIPTION
**Pull request by smcavallo**
Signed-off-by: smcavallo <smcavallo@hotmail.com>

Issue #1059, if available:
https://github.com/aws-controllers-k8s/community/issues/1059

Description of changes:
aws-sdk-go version bump, 1.37.10 -> 1.42.0 to unblock crossplane

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by A-Hilaly** [comment]
Do we have any idea on how many controllers will not build with SDK 1.42.0 ?
/approve

**Comment by smcavallo** [comment]
> 
> 
> Do we have any idea on how many controllers will not build with SDK 1.42.0 ? /approve

@A-Hilaly - What is the best way to test this?  I don't know offhand but I can take a shot at trying to build.

**Comment by A-Hilaly** [comment]
@smcavallo We discussed this during the community meeting and we will merge and release specific versions of runtime and code-gen soon.

>What is the best way to test this?

Best way would be to bump the aws-sdk-go version in ack-generate and regenerate all the controllers :)
Also every `go.mod` file should point to `github.com/aws/aws-sdk-go` v1.42.0 in this case

**Comment by surajkota** [comment]
Hi @smcavallo, `1.37.10 -> 1.42.0 to unblock crossplane` what does this mean?

**Comment by jaypipes** [comment]
@smcavallo the ACK core team is working on validating this for a controller before we LGTM it. Hoping to have this merged Monday. Note that we do not think the corresponding PR to code-generator will be necessary, since what you need in the ACK runtime with aws-sdk-go@v1.42.0 is the Session handling (for FIPS endpoints), and not the updated API models for the individual services.

**Comment by A-Hilaly** [comment]
Closing in favor of upgrade to v1.42.35

**Pull request closed without merging**
